# Generated by Django 3.1.14 on 2022-11-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_pokemon_evolved_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='evolved_from',
            new_name='previous_evolution',
        ),
    ]
